spring.application.name=IdentityService

server.port=8080

#making apis strict to this port
server.servlet.session.cookie.same-site=strict

#database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore-users
spring.datasource.username=postgres
spring.datasource.password=tiger
spring.datasource.driver-class-name=org.postgresql.Driver

#hibernate (to create tables automatic via JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#sending data to mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= 
spring.mail.password= 
#jkiq anbd udpi wmwj - bv2.1
#usal nitf nypz ijcl - bv2
#ndrx ovtq fbdf bmls - bv1 (deprecated)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
