import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import Theme from "./components/common/Theme";
import { Toaster } from "react-hot-toast";
import Providers from "./components/common/Providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

export const metadata = {
  title: "BookStore V2",
  description: "Generated by NextJS",
};

const themeScript = `
  (function() {
    try {
      const savedTheme = localStorage.getItem('theme');
      const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
      const isDark = savedTheme === 'dark' || (!savedTheme && prefersDark);
      document.documentElement.classList.toggle('dark', isDark);
    } catch (error) {
      document.documentElement.classList.remove('dark');
    }
  })();
`;

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.variable} ${playfair.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
        <Providers>
          <Theme />
          <Toaster position="top-right" toastOptions={{
            duration: 4000, style: {
              background: "var(--background)",
              color: "var(--foreground)",
              borderRadius: "10px",
              border: "1px solid var(--foreground)",
              boxShadow: "0px 1px 1px var(--foreground)"
            }
          }} />
          {children}
        </Providers>
      </body>
    </html>
  );
}
