spring.application.name=CommonService

server.port = 8084

#making apis strict to this port
server.servlet.session.cookie.same-site=strict

#database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore-common
spring.datasource.username=postgres
spring.datasource.password=tiger
spring.datasource.driver-class-name=org.postgresql.Driver

#hibernate (to create tables automatic via JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
