spring.config.import=file:.env[.properties]

spring.application.name=BookService

server.port=${BOOK_SERVER_PORT:8081}

#making apis strict to this port
server.servlet.session.cookie.same-site=strict

#database configuration
spring.datasource.url=${DB_BOOK_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#hibernate (to create tables automatic via JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [requestId=%X{requestId:-}] %logger{36} - %msg%n
